<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ErfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErfRepository extends EntityRepository
{
    public function findByErfNo($erfNo)
    {
        $results = $this->getEntityManager()
                ->createQuery(
                        'SELECT e FROM AppBundle:Erf e '
                        . 'WHERE e.erfNo = :erf_no')
                ->setParameter('erf_no', $erfNo)
                ->setMaxResults(1)
                ->getOneOrNullResult();

        return $results;
    }
}
