<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository {

    public function getCurrentBalance() {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT p FROM AppBundle:Payment p ORDER BY p.created DESC'
                        )->setMaxResults(1)->getOneOrNullResult();
    }
    
    public function getRecent() {
        return $this->getEntityManager()
                        ->createQuery('SELECT p FROM AppBundle:Payment p ORDER BY p.created DESC')
                ->setMaxResults(10)
                ->getResult();
    }

    public function getBarGraphValues() {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT p FROM AppBundle:Payment p GROUP BY p.created ORDER BY p.created ASC '
                    )->getResult();

        return $results;
    }

}
