<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentAllocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentAllocationRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array(), array('created' => 'DESC'));
    }

    public function deleteByMonth($month)
    {
        $entities = $this->findBy(array('month' => $month));
        $em = $this->getEntityManager();
        foreach ($entities as $entity) {
            $em->remove($entity);
        }
        $em->flush();
    }

    public function allocateBySection($id)
    {
        $em = $this->getEntityManager();

        $entities = $em->getRepository('AppBundle:Erf')->findBy(array('sectionId' => $id));

        $rate = $em->getRepository('AppBundle:Rate')->findOneBy(array('id' => 1));
        
        foreach ($entities as $result) {
            
            $allocation = new PaymentAllocation();
            $allocation->setErf($result);
            $allocation->setAmount($rate->getAmount());
            $date = new \DateTime();
            $allocation->setMonth($date->format('F'));
            $allocation->setCreated($date);
            $allocation->setUpdated($date);
            
            $em->persist($allocation);
        }

        $em->flush();
        $em->clear();
    }
}