<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends EntityRepository
{

    public function getRate()
    {
        $results = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('r')
                ->from('AppBundle:Rate', 'r')
                ->getQuery()
                ->getSingleScalarResult();

        return $results;
    }

}
